spring:
  profiles:
    active: local
    include: common
  main:
    banner-mode: off
    web-application-type: none
  shell:
    history.enabled: false

application:
  services:
    server-url: http://localhost:8080/ws