server:
  http2.enabled: true
  https:
    enabled: true
    port: 8443
    key-password: tomcat
    key-store-password: tomcat
    key-store: classpath:cert/certificate.p12
    ciphers: TLS_RSA_WITH_AES_256_CBC_SHA
  tomcat:
    accesslog:
      enabled: true
      pattern: "%t %a '%r' %s (%D ms)"
