server:
  port: 8080

spring:
  profiles.active: local,common
  application.name: GraphQL
  main.banner-mode: off
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  graphql:
    websocket.path: /graphql
    graphiql.enabled: true
