spring:
  profiles:
    active: local
    include: common
  main:
    banner-mode: off
    web-application-type: none

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        max-wait-duration-in-half-open-state: 10s

logging.level:
  io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine: debug
